# docker-compose.yml
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./doctor-appointment-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/doctor
      JWT_SECRET: change-me-please
      FRONTEND_ORIGIN: http://localhost:8080
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./doctor-appointment-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:5000"
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo_data:
