version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: doctor-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./doctor-appointment-backend
    container_name: doctor-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./doctor-appointment-backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./doctor-appointment-frontend
      args:
        VITE_API_BASE: http://backend:5000
    container_name: doctor-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
