services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./doctor-appointment-backend
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/doctor
      JWT_SECRET: change-me-please
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./doctor-appointment-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo_data:
